### PR TITLE
add an actual game

### PR DESCRIPTION
**Pull request by DillyzThe1**
hold up and down or hit enter for debug when running via console

### CODE REVIEW

**Review by impostor5875 — APPROVED** [review]
i forgor

**Review by impostor5875 — APPROVED** [review]
i approve II

**Comment by DillyzThe1** [comment]
fred

**Review by impostor5875 — APPROVED** [review]
i approve III

**Review by impostor5875 — APPROVED** [review]
did i mention that i approve

**Comment by DillyzThe1** [comment]
no

**Review by impostor5875 — CHANGES_REQUESTED** [review]
v

**Review by impostor5875 — APPROVED** [review]
oh and also i approve

**Review by impostor5875 — APPROVED** [review]
i approve one last time

**Review by impostor5875 — APPROVED** [review]
actually wait no one more

**Review by impostor5875 — APPROVED** [review]
fred

**Review by impostor5875 — APPROVED** [review]
momazos diego

**Review by impostor5875 — APPROVED** [review]
good

**Comment by DillyzThe1** [comment]
fred

**Review by impostor5875 — APPROVED** [review]
ok

**Comment by DillyzThe1** [comment]
"ummmm actually you could just merge the pull request" 🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓

**Review by impostor5875 — APPROVED** [review]
come on when will the owner merge this pull request

**Comment by DillyzThe1** [comment]
image

**Review by impostor5875 — APPROVED** [review]
oh wait i'm the owner

**Review by impostor5875 — APPROVED** [review]
and also i approve

**Comment by DillyzThe1** [comment]
image

**Review by impostor5875 — COMMENTED** [review]
btw i approve

**Review by DillyzThe1 — COMMENTED** [review]
i **can't** approve 🤓🤓🤓🤓💀💀💀💀💀💀💀💀💀

**Pull request merged**
